apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-argo-application
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodeapp-image=ubnd/node-app
    argocd-image-updater.argoproj.io/nodeapp-image.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/dtnguyen22/node-app-deploy.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
