apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/dtnguyen22/node-app-deploy.git
    targetRevision: HEAD
    path: dev
  destination:
    #internal kubernetes server
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    #create ns if does not exist
    syncOptions:
      - CreateNamespace=true

    automated:
      #undo manually changes
      selfHeal: true
      #auto delete old resources after sync
      prune: true
