apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodeapp
  replicas: 3
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: ubnd/node-app:21
          ports:
            - containerPort: 8080
