apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - port: 8080
      protocol: TCP
      #targetPort: 8080
      nodePort: 9090
