apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nodeapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - image: ubnd/node-app:latest
          name: nodeapp
          ports:
            - containerPort: 8080
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodeapp-argo-application
  namespace: argocd
spec:
  destination:
    namespace: myapp
    server: https://kubernetes.default.svc
  project: default
  source:
    path: dev
    repoURL: https://github.com/dtnguyen22/node-app-deploy.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
